# Fixtures file for puppet_spec_helper in the task: rake spec
fixtures:
  symlinks:
    st2: "#{source_dir}"
  forge_modules:
    httpauth: "jamtur01/httpauth"
    stdlib: "puppetlabs/stdlib"
    staging: "puppet/staging"
    apt: "puppetlabs/apt"
    epel: "stahnma/epel"
    concat: "puppetlabs/concat"
    sudo: "saz/sudo"
    python: "puppet/python"
    gcc: "puppetlabs/gcc"
    inifile: "puppetlabs/inifile"
    mongodb: "puppet/mongodb"
    postgresql: "puppetlabs/postgresql"
    rabbitmq: "puppet/rabbitmq"
    packagecloud: "computology/packagecloud"
    selinux: "puppet/selinux"
    nginx: "puppet/nginx"
    nodejs: "puppet/nodejs"
  repositories:
    # needed for Litmus
    # https://github.com/puppetlabs/puppet_litmus/wiki/Converting-a-module-to-use-Litmus
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
