---
driver:
  name: docker
  privileged: true
  use_sudo: false
  require_chef_omnibus: false

transport:
  name: sftp

provisioner:
  # in the container, run: puppet apply
  name: puppet_apply
  # manifest to execute
  manifest: test/fullinstall_python36.pp
  # unused, but required
  modules_path: ./modules
  # don't have kitchen-puppet install chef by default
  require_chef_for_busser: false
  # don't have kitchen-puppet install puppet by default (done in Dockerfile)
  require_puppet_collections: false
  # no longer resolve with librarian-puppet because of dependency hell
  resolve_with_librarian_puppet: false
  # use r10k for installing dependencies so we have the explicitly installed
  # and avoid ordering problems and random minor version clashes
  resolve_with_r10k: true
  # If you do not enable puppet_detailed_exitcodes, the provisioner only failes
  # if the manifest can not be compiled.
  puppet_detailed_exitcodes: true
  # Exit code details:
  # https://github.com/neillturner/kitchen-puppet/blob/master/provisioner_options.md#checking-puppet-apply-success-with-puppet_detailed_exitcodes
  #   0: The run succeeded with no changes or failures; the system was already in the desired state.
  #   1: The run failed, or wasn't attempted due to another run already in progress.
  #   2: The run succeeded, and some resources were changed.
  #   4: The run succeeded, and some resources failed.
  #   6: The run succeeded, and included both changes and failures.
  puppet_whitelist_exit_code:
    - 0
    - 2

platforms:
  # CentOS7 with Systemd - Puppet 6
  - name: centos7-puppet6
    driver:
      platform: centos
      dockerfile: build/centos7-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/centos7-puppet6/Puppetfile

  # CentOS7 with Systemd - Puppet 7
  - name: centos7-puppet7
    driver:
      platform: centos
      dockerfile: build/centos7-puppet7/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/centos7-puppet7/Puppetfile

  # RockyLinux 8 - Puppet 6
  - name: rocky8-puppet6
    driver:
      platform: rockylinux
      dockerfile: build/rocky8-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/rocky8-puppet6/Puppetfile
      manifest: test/fullinstall_python38.pp

  # RockyLinux 8 - Puppet 7
  - name: rocky8-puppet7
    driver:
      platform: rockylinux
      dockerfile: build/rocky8-puppet7/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/rocky8-puppet7/Puppetfile
      manifest: test/fullinstall_python38.pp

  # RockyLinux 8 - Puppet 7
  - name: rocky8-puppet7-hatest
    driver:
      platform: rockylinux
      dockerfile: build/rocky8-puppet7/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/rocky8-puppet7/Puppetfile
      manifest: test/fullinstall_hatest.pp

  # Ubuntu Bionic with Systemd - Puppet 6
  - name: ubuntu18-puppet6
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu18-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu18-puppet6/Puppetfile

  # Ubuntu Bionic with Systemd - Puppet 7
  - name: ubuntu18-puppet7
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu18-puppet7/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu18-puppet7/Puppetfile

  # Ubuntu Focal with Systemd - Puppet 6
  - name: ubuntu20-puppet6
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu20-puppet6/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu20-puppet6/Puppetfile
      manifest: test/fullinstall_python38.pp

  # Ubuntu Focal with Systemd - Puppet 7
  - name: ubuntu20-puppet7
    driver:
      platform: ubuntu
      dockerfile: build/ubuntu20-puppet7/Dockerfile.kitchen
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    provisioner:
      puppetfile_path: build/ubuntu20-puppet7/Puppetfile
      manifest: test/fullinstall_python38.pp

suites:
  - name: default

verifier:
  name: inspec
  sudo: true
  # by default `sudo` doesn't set many of the environment variables.
  # we need to tell sudo to set the $HOME env var to /root.
  # this way it picks up ~/.st2/config for the root user, configured by Puppet
  # this ~/.st2/config contains auth credentials to test out st2 comamnds
  # via inspec
  sudo_options: "HOME=/root -u root"
  inspec_tests:
    - path: test/integration/stackstorm
